# Generated by Django 2.1.3 on 2018-11-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('postal_code', models.IntegerField(max_length=5)),
            ],
        ),
    ]
