# Generated by Django 2.1.3 on 2018-12-05 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0008_auto_20181130_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='eval',
        ),
        migrations.AddField(
            model_name='place',
            name='evaluations',
            field=models.ManyToManyField(related_name='evaluations', through='places.EvalPlace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
